# Generated by Django 3.2.16 on 2022-12-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Images',
            new_name='image',
        ),
    ]
